// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechHive.AI.Support.Data;

#nullable disable

namespace TechHive.AI.Support.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251122153915_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechHive.AI.Support.Models.FaqItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FaqItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Shipping usually takes between 2 to 5 business days within Saudi Arabia.",
                            Question = "What is the shipping time inside Saudi Arabia?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "You can return products within 14 days of delivery if they are in original condition.",
                            Question = "What is your return policy?"
                        });
                });

            modelBuilder.Entity("TechHive.AI.Support.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Latest Apple flagship smartphone.",
                            Name = "iPhone 15 Pro",
                            Price = 4500m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 2,
                            Description = "High-end Samsung smartphone.",
                            Name = "Galaxy S24",
                            Price = 3800m,
                            Stock = 10
                        });
                });

            modelBuilder.Entity("TechHive.AI.Support.Models.StoreSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StoreSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "StoreName",
                            Value = "TechHive"
                        },
                        new
                        {
                            Id = 2,
                            Key = "SupportEmail",
                            Value = "support@techhive.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
